# Generated by Django 3.2.16 on 2022-10-21 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('credit_limit', models.FloatField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('date', models.DateField(null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('vat', models.FloatField(blank=True, null=True)),
                ('amount_due', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'invoice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('payment_method', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'payment_method',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('units', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('product_type', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'product_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('receipt_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('date', models.DateField(null=True)),
                ('payment_method', models.CharField(blank=True, max_length=10, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=10, null=True)),
                ('total_received', models.FloatField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'receipt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('key', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('invoice_no', models.ForeignKey(db_column='invoice_no', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='report.invoice')),
                ('item_no', models.IntegerField()),
                ('quantity', models.IntegerField(null=True)),
                ('unit_price', models.FloatField(null=True)),
                ('product_total', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'invoice_line_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReceiptLineItem',
            fields=[
                ('receipt_no', models.ForeignKey(db_column='receipt_no', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='report.receipt')),
                ('item_no', models.IntegerField()),
                ('invoice_no', models.CharField(max_length=100)),
                ('amount_paid_here', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'receipt_line_item',
                'managed': False,
            },
        ),
        # migrations.CreateModel(
        #     name='Promotion',
        #     fields=[
        #         ('event', models.CharField(db_column='event', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='report.promotion')),
        #         ('discount', models.IntegerField(null=True)),
        #         ('vat', models.IntegerField(null=True)),
        #         ('amount_due', models.IntegerField(null=True)),
        #     ],
        #     options={
        #         'db_table': 'promotion',
        #         'managed': False,
        #     },
        # ),
    ]
